name: Security - Scheduled

on:
  schedule:
    - cron: "0 2 * * *"

  workflow_dispatch:

permissions:
  contents: read

jobs:

  trivy-sca:
    name: Trivy Dependency Scan
    uses: ./.github/workflows/security /sca-trivy.yml

  notify-status:

    name: Security Summary

    runs-on: ubuntu-latest

    needs:
      - trivy-sca

    if: always()

    steps:

      - name: Security Scan Completed
        run: |
          echo "Security workflow completed"
